### ISSUE TITLE
Should not include check_dhcp binary

### ISSUE THREAD

**Issue by russellb** [schmaustech/kni-preflight#2]
I see the check_dhcp binary in the source tree.  It appears to be a build of this:

https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins-root/check_dhcp.c

Since this is GPL licensed, you can't include a binary like this without also distributing the source.  It's probably best to not include the binary directly at all.

**Comment by schmaustech** [comment]
@russellb agree - I am looking at what options we have to do something different.

**Comment by schmaustech** [comment]
@russellb this has been replaced by a script I wrote called check_dhcp.py.  The original check_dhcp binary has been removed.
