### ISSUE TITLE
rerunning kni-preflight creates install-config.yaml

### ISSUE THREAD

**Issue by rlopez133** [schmaustech/kni-preflight#3]
Rerunning the kni-preflight will delete the existing install-config.yaml . My thinking is if it already sees a install-config.yaml existing, ask if they are OK with deleting OR if there is one existing add .orig to the existing one. Basically some sort of check so as if not to hose your file if you decided you wanted to re-see the output.

**Comment by schmaustech** [comment]
I am now backing up previous as install-config.yaml.orig.
